language: java
sudo: false

jdk:
  - openjdk8
  - openjdk11

env:
  - TESTFOLDER=jraft-core
  - TESTFOLDER=jraft-rheakv/rheakv-core
  - TESTFOLDER=jraft-rheakv/rheakv-pd

cache:
  directories:
  - $HOME/.m2

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - travis_retry mvn --projects $TESTFOLDER clean test

script:
  - sh ./tools/check_format.sh
